title: Is Your Community Ready to Evacuate with EVs? 
description: This project, led by UC Merced, UC Davis, UC Santa Cruz, and UC Berkeley, helps communities assess and improve their readiness for evacuations using electric vehicles (EVs). Explore our tools, reports, and case studies supporting resilient and equitable emergency planning.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman


